config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/home', to: 'static_pages#home'
  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = "Skunk Works"
    if page_title.empty?
      base_title
    else
      page_title = "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Skunk Works", root_path, class: "navbar-brand main-logo" %>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Log in",  '#' %></li>
            <li><%= link_to "Sign up",  signup_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
      </div>
    </nav>
    <main class="container text-center">
      <%= yield %>
    </main>
    <footer>
      <p>Copyright 2019 Skunk Works</p>
          <ul class="footer-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
    </footer>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div>
  <h1><%= yield(:title) %></h1>
  <p>So, now that you're here..</p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div>
  <h1><%= yield(:title) %></h1>
  <p>Contact us!</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div>
  <h1><%= yield(:title) %></h1>
  <p>Reach out and leave a message if you need assistance!</p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="text-center jumbotron">
  <h1>Skunk Works</h1>
  <p>This is the homepage Lockheed Martin's Skunk Works secret division!</p>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to  image_tag("skunk_patch.jpg", alt: "Skunkerino"), 'https://en.wikipedia.org/wiki/Skunk_Works' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div>
  <h1>Sign up!</h1>
  <p>Users will sign up here..</p>
</div>